# Generated by Django 3.0.6 on 2020-08-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('nacimento', models.DateTimeField(verbose_name='data de nacimento')),
                ('status', models.CharField(blank=True, choices=[('r', 'Registrado'), ('m', 'Matriculado'), ('e', 'expulso')], default='r', help_text='status do aluno', max_length=1)),
            ],
        ),
    ]
